import { PGlite } from "@electric-sql/pglite";
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { metadataSnapshotQuery, type ManagedSchema } from "../../scripts/db-catalog-snapshot";
import { STORAGE_POLICIES, sha256 } from "../../scripts/db-migration-plan";

// Synthetic catalog only, in memory, with the same PGlite setup as inventory
// tests. No migration sources, environment files, CLI imports or external DBs.
vi.mock("postgres", () => { throw new Error("External database clients are forbidden in catalog tests."); });
let db: PGlite;

type Grant = { grantor: string; grantee: string; privilege: string; grantable: boolean };
type Named = { name: string };
type Relation = Named & {
  kind: string; owner: string; acl: Grant[]; rls: boolean; partition: boolean; partitionBound: string | null; parents: string[];
  view: string | null; options: string[];
  columns: (Named & { acl: Grant[]; identity: string; generated: string; default: string | null })[];
  indexes: (Named & { definition: string; valid: boolean })[];
  constraints: (Named & { definition: string; type: string })[];
  triggers: (Named & { internal: boolean; definition: string })[];
  policies: (Named & { using: string | null; check: string | null; roles: string[] })[];
};
type Metadata = {
  schema: Named & { owner: string; acl: Grant[] };
  relations: Relation[];
  types: (Named & { kind: string; owner: string; acl: Grant[]; labels: string[] | null; notNull: boolean; default: string | null })[];
  routines: (Named & { kind: string; arguments: string; result: string | null; acl: Grant[] })[];
  defaultPrivileges: { role: string; namespace: string; type: string; acl: Grant[] }[];
};

function named<T extends Named>(entries: T[], name: string): T {
  const entry = entries.find((candidate) => candidate.name === name);
  if (!entry) throw new Error("Missing synthetic catalog fixture.");
  return entry;
}

beforeAll(async () => {
  db = new PGlite();
  await db.exec(`
    create role synthetic_reader nologin nosuperuser nobypassrls;
    create role synthetic_group nologin nosuperuser nobypassrls;
    grant synthetic_group to synthetic_reader;
    create schema auth;
    create schema storage;
    create type public.synthetic_status as enum ('draft', 'active');
    create domain public.synthetic_nonempty as text not null default 'synthetic' check (value <> '');
    create type public.synthetic_pair as (label text, amount integer);
    create table public.synthetic_catalog (
      id bigint generated by default as identity primary key,
      null_acl text, empty_acl text, granted_acl text,
      label text not null default 'synthetic',
      amount integer not null default 0 check (amount >= 0),
      status public.synthetic_status not null default 'draft',
      normalized text generated always as (lower(label)) stored
    );
    grant select (empty_acl, granted_acl) on public.synthetic_catalog to synthetic_reader;
    revoke select (empty_acl) on public.synthetic_catalog from synthetic_reader;
    grant update (granted_acl) on public.synthetic_catalog to synthetic_reader with grant option;
    create index synthetic_partial_idx on public.synthetic_catalog (lower(label)) where amount > 0;
    create view public.synthetic_view with (security_barrier = true) as select id, label from public.synthetic_catalog;
    create materialized view public.synthetic_materialized as select id, amount from public.synthetic_catalog with no data;
    create table public.synthetic_partitioned (id integer, part integer) partition by range (part);
    create table public.synthetic_partition partition of public.synthetic_partitioned for values from (0) to (100);
    create function public.synthetic_add(state integer, value integer) returns integer
      language sql immutable strict as $$ select state + value $$;
    create aggregate public.synthetic_total(integer) (sfunc = public.synthetic_add, stype = integer, initcond = '0');
    create function public.synthetic_identity(value text) returns text
      language sql immutable strict as $$ select value $$;
    create function public.synthetic_identity(value integer) returns integer
      language sql immutable strict as $$ select value $$;
    create procedure public.synthetic_noop() language sql as $$ select 1 $$;
    create function public.synthetic_before() returns trigger language plpgsql as $$ begin return new; end $$;
    create trigger synthetic_before before insert or update on public.synthetic_catalog
      for each row execute function public.synthetic_before();
    alter table public.synthetic_catalog enable row level security;
    create policy synthetic_public_select on public.synthetic_catalog for select to synthetic_reader using (amount >= 0);
    create policy synthetic_public_update on public.synthetic_catalog for update to synthetic_reader
      using (amount >= 0) with check (amount >= 1);
    create policy shagun_media_admin_read on public.synthetic_catalog for select using (false);
    create table auth.users (id uuid primary key);
    create table auth.synthetic_links (id uuid primary key references auth.users(id));
    create table storage.objects (id uuid primary key, bucket_id text, name text);
    alter table storage.objects enable row level security;
    create policy synthetic_sibling_policy on storage.objects for select to synthetic_reader
      using (bucket_id = 'synthetic-other');
    create policy shagun_media_not_reserved on storage.objects for select using (false);
    create table storage.synthetic_other_objects (id uuid primary key);
    create policy shagun_media_admin_read on storage.synthetic_other_objects for select using (false);
    grant usage on schema public, auth, storage to synthetic_reader;
    grant usage on sequence public.synthetic_catalog_id_seq to synthetic_reader;
    alter default privileges in schema public grant select on tables to synthetic_reader;
  `);
});

beforeEach(async () => { await db.exec("begin; set local search_path = pg_catalog"); });
afterEach(async () => { await db.exec("rollback"); });
afterAll(async () => { await db?.close(); });

async function snapshot(schema: ManagedSchema = "public", newStorage = false, newInventory = false) {
  const query = metadataSnapshotQuery(schema, newStorage, newInventory);
  const result = await db.query<{ snapshot: string }>(query.text, query.parameters);
  expect(result.rows).toHaveLength(1);
  return result.rows[0].snapshot;
}

async function metadata(schema: ManagedSchema = "public", newStorage = false, newInventory = false): Promise<Metadata> {
  // These synthetic results stay in memory. Comparisons report hashes/booleans,
  // never a catalog dump, routine body, credential or managed-service record.
  return JSON.parse(await snapshot(schema, newStorage, newInventory)) as Metadata;
}

describe("isolated PostgreSQL literal probes (not managed-service diagnostics)", () => {
  it("rejects an empty ACL literal with 22023: ACL arrays must be one-dimensional", async () => {
    await expect(db.query("select * from pg_catalog.aclexplode('{}'::aclitem[])"))
      .rejects.toMatchObject({ code: "22023", message: "ACL arrays must be one-dimensional" });
  });

  it("reproduces the original column expression on a normal NULL attacl", async () => {
    await expect(db.query(`select g.* from pg_attribute a
      cross join lateral pg_catalog.aclexplode(coalesce(a.attacl, '{}'::aclitem[])) g
      where a.attrelid = 'public.synthetic_catalog'::regclass and a.attname = 'null_acl'`))
      .rejects.toMatchObject({ code: "22023", message: "ACL arrays must be one-dimensional" });
  });

  it("treats a NULL ACL as no explicit grants", async () => {
    const result = await db.query<{ empty: boolean }>(
      "select not exists (select 1 from pg_catalog.aclexplode(null::aclitem[])) as empty",
    );
    expect(result.rows[0].empty).toBe(true);
  });

  it("keeps uppercase T for type USAGE; lowercase t is tablespace CREATE", async () => {
    const result = await db.query<{ type_usage: boolean; tablespace_create: boolean }>(`select
      (select bool_and(privilege_type = 'USAGE') from aclexplode(acldefault('T', r.oid))) as type_usage,
      (select bool_and(privilege_type = 'CREATE') from aclexplode(acldefault('t', r.oid))) as tablespace_create
      from pg_roles r where r.rolname = current_user`);
    expect(result.rows[0]).toEqual({ type_usage: true, tablespace_create: true });
  });

  it("supports aggregate and function result introspection without reading bodies", async () => {
    const result = await db.query<{ aggregate_result: boolean; function_result: boolean }>(`select
      pg_get_function_result('public.synthetic_total(integer)'::regprocedure) = 'integer' as aggregate_result,
      pg_get_function_result('public.synthetic_identity(text)'::regprocedure) = 'text' as function_result`);
    expect(result.rows[0]).toEqual({ aggregate_result: true, function_result: true });
  });

  it("canonicalizes a fully revoked column ACL to NULL while retaining other grants", async () => {
    const result = await db.query<{ null_acl: boolean; revoked_acl: boolean; granted_acl: boolean }>(`select
      bool_and(a.attacl is null) filter (where a.attname = 'null_acl') as null_acl,
      bool_and(a.attacl is null) filter (where a.attname = 'empty_acl') as revoked_acl,
      bool_and(cardinality(a.attacl) > 0) filter (where a.attname = 'granted_acl') as granted_acl
      from pg_attribute a where a.attrelid = 'public.synthetic_catalog'::regclass and a.attnum > 0`);
    expect(result.rows[0]).toEqual({ null_acl: true, revoked_acl: true, granted_acl: true });
  });

  it("does not hide the error for a nonempty multidimensional ACL literal", async () => {
    await expect(db.query(`select g.* from pg_roles r cross join lateral
      aclexplode(nullif(array[acldefault('T', r.oid)], '{}'::aclitem[])) g where r.rolname = current_user`))
      .rejects.toMatchObject({ code: "22023", message: "ACL arrays must be one-dimensional" });
  });
});

describe("checked-in metadata snapshot SQL", () => {
  it.each(["public", "auth", "storage"] as const)("snapshots %s deterministically with unchanged logical catalogs", async (schema) => {
    await db.exec("set transaction read only");
    const first = sha256(await snapshot(schema));
    expect(first).toMatch(/^[a-f0-9]{64}$/);
    expect(sha256(await snapshot(schema))).toBe(first);
  });

  it("keeps NULL/revoked columns empty and every nonempty privilege, grant option and OID", async () => {
    const catalog = await metadata();
    const table = named(catalog.relations, "synthetic_catalog");
    expect(named(table.columns, "null_acl").acl.length === 0).toBe(true);
    expect(named(table.columns, "empty_acl").acl.length === 0).toBe(true);
    const grants = named(table.columns, "granted_acl").acl;
    const reader = (await db.query<{ id: string }>("select oid::text as id from pg_roles where rolname = 'synthetic_reader'")).rows[0].id;
    expect(grants.length === 2).toBe(true);
    // public's schema owner can be pg_database_owner; the table owner issues
    // these column grants. Pin that object's OID, not the containing schema's.
    expect(grants.every((grant) => grant.grantee === reader && grant.grantor === table.owner)).toBe(true);
    expect(grants.some((grant) => grant.privilege === "SELECT" && !grant.grantable)).toBe(true);
    expect(grants.some((grant) => grant.privilege === "UPDATE" && grant.grantable)).toBe(true);
  });

  it("normalizes a stored empty column ACL without changing the logical snapshot", async () => {
    const before = sha256(await snapshot());
    // GRANT/REVOKE normally canonicalizes an empty column ACL to NULL (above).
    // Seed the equivalent explicit-empty representation ONLY in this isolated
    // synthetic catalog to exercise the production query, not a SQL mock.
    await db.exec(`update pg_catalog.pg_attribute set attacl = '{}'::aclitem[]
      where attrelid = 'public.synthetic_catalog'::regclass and attname = 'empty_acl'`);
    const result = await db.query<{ empty: boolean }>(`select attacl is not null and cardinality(attacl) = 0 as empty
      from pg_attribute where attrelid = 'public.synthetic_catalog'::regclass and attname = 'empty_acl'`);
    expect(result.rows[0].empty).toBe(true);
    expect(sha256(await snapshot())).toBe(before);
  });

  it("retains types, aggregates, overloaded routines, views, indexes, partitions, constraints and policies", async () => {
    const catalog = await metadata();
    const table = named(catalog.relations, "synthetic_catalog");
    const status = named(catalog.types, "synthetic_status");
    expect(status.kind === "e" && status.labels?.join(",") === "draft,active").toBe(true);
    expect(status.acl.some((grant) => grant.grantee === "0" && grant.privilege === "USAGE")).toBe(true);
    expect(status.acl.some((grant) => grant.grantee === status.owner && grant.privilege === "USAGE")).toBe(true);
    expect(named(catalog.types, "synthetic_nonempty").kind === "d").toBe(true);
    expect(named(catalog.types, "synthetic_nonempty").notNull).toBe(true);
    expect(named(catalog.types, "synthetic_pair").kind === "c").toBe(true);
    expect(named(catalog.types, "_synthetic_status").kind === "b").toBe(true);
    expect(named(catalog.routines, "synthetic_total").kind === "a").toBe(true);
    expect(named(catalog.routines, "synthetic_total").result === "integer").toBe(true);
    expect(catalog.routines.filter((routine) => routine.name === "synthetic_identity").length === 2).toBe(true);
    expect(named(catalog.routines, "synthetic_noop").kind === "p").toBe(true);
    expect(named(catalog.routines, "synthetic_noop").result === null).toBe(true);
    expect(named(catalog.relations, "synthetic_view").view?.includes("synthetic_catalog")).toBe(true);
    expect(named(catalog.relations, "synthetic_view").options.includes("security_barrier=true")).toBe(true);
    expect(named(catalog.relations, "synthetic_materialized").kind === "m").toBe(true);
    expect(named(catalog.relations, "synthetic_materialized").view?.includes("synthetic_catalog")).toBe(true);
    expect(named(catalog.relations, "synthetic_partitioned").kind === "p").toBe(true);
    const partition = named(catalog.relations, "synthetic_partition");
    expect(partition.partition && partition.parents.length === 1 && partition.partitionBound !== null).toBe(true);
    expect(named(catalog.relations, "synthetic_catalog_id_seq").kind === "S").toBe(true);
    expect(named(table.columns, "id").identity === "d").toBe(true);
    expect(named(table.columns, "normalized").generated === "s").toBe(true);
    expect(named(table.columns, "label").default !== null).toBe(true);
    expect(table.rls).toBe(true);
    expect(named(table.indexes, "synthetic_partial_idx").valid).toBe(true);
    expect(named(table.indexes, "synthetic_partial_idx").definition.includes("WHERE")).toBe(true);
    expect(table.constraints.some((constraint) => constraint.type === "c" && constraint.definition.includes("amount"))).toBe(true);
    expect(named(table.triggers, "synthetic_before").definition.includes("BEFORE INSERT OR UPDATE")).toBe(true);
    expect(named(table.policies, "synthetic_public_update").check?.includes("amount >= 1")).toBe(true);
    expect(named(table.policies, "synthetic_public_select").roles.every((role) => /^\d+$/.test(role))).toBe(true);
    expect(catalog.defaultPrivileges.some((entry) => entry.acl.some((grant) => grant.privilege === "SELECT"))).toBe(true);
  });

  const emptyAclCases: {
    name: string; schema: ManagedSchema; revoke: string; probe: string; grants: (catalog: Metadata) => Grant[];
  }[] = [
    {
      name: "schema", schema: "auth",
      revoke: "revoke all on schema auth from public, current_user, synthetic_reader",
      probe: "select cardinality(nspacl) = 0 as empty from pg_namespace where nspname = 'auth'",
      grants: (catalog) => catalog.schema.acl,
    },
    {
      name: "table", schema: "public",
      revoke: "revoke all on table public.synthetic_catalog from public, current_user",
      probe: "select cardinality(relacl) = 0 as empty from pg_class where oid = 'public.synthetic_catalog'::regclass",
      grants: (catalog) => named(catalog.relations, "synthetic_catalog").acl,
    },
    {
      name: "sequence", schema: "public",
      revoke: "revoke all on sequence public.synthetic_catalog_id_seq from public, current_user, synthetic_reader",
      probe: "select cardinality(relacl) = 0 as empty from pg_class where oid = 'public.synthetic_catalog_id_seq'::regclass",
      grants: (catalog) => named(catalog.relations, "synthetic_catalog_id_seq").acl,
    },
    {
      name: "type", schema: "public",
      revoke: "revoke all on type public.synthetic_status from public, current_user",
      probe: "select cardinality(typacl) = 0 as empty from pg_type where oid = 'public.synthetic_status'::regtype",
      grants: (catalog) => named(catalog.types, "synthetic_status").acl,
    },
    {
      name: "routine", schema: "public",
      revoke: "revoke all on function public.synthetic_add(integer, integer) from public, current_user",
      probe: "select cardinality(proacl) = 0 as empty from pg_proc where oid = 'public.synthetic_add(integer,integer)'::regprocedure",
      grants: (catalog) => named(catalog.routines, "synthetic_add").acl,
    },
  ];

  it.each(emptyAclCases)("does not replace an explicit empty $name ACL with default owner grants", async ({ schema, revoke, probe, grants }) => {
    const before = await snapshot(schema);
    expect(grants(JSON.parse(before) as Metadata).length > 0).toBe(true);
    await db.exec(revoke);
    expect((await db.query<{ empty: boolean }>(probe)).rows[0].empty).toBe(true);
    const after = await snapshot(schema);
    expect(grants(JSON.parse(after) as Metadata).length === 0).toBe(true);
    expect(sha256(after)).not.toBe(sha256(before));
  });

  it("retains explicitly empty global default privileges alongside scoped grants", async () => {
    const before = sha256(await snapshot());
    await db.exec("alter default privileges revoke all on tables from current_user");
    const result = await db.query<{ empty: boolean }>(`select exists(select 1 from pg_default_acl
      where defaclnamespace = 0 and defaclobjtype = 'r' and cardinality(defaclacl) = 0) as empty`);
    expect(result.rows[0].empty).toBe(true);
    const catalog = await metadata();
    expect(catalog.defaultPrivileges.some((entry) => entry.namespace === "0" && entry.type === "r" && entry.acl.length === 0)).toBe(true);
    expect(catalog.defaultPrivileges.some((entry) => entry.namespace !== "0" && entry.acl.length > 0)).toBe(true);
    expect(sha256(await snapshot())).not.toBe(before);
  });

  it.each([
    ["column grant", "grant insert (granted_acl) on public.synthetic_catalog to synthetic_reader"],
    ["column grant option", "revoke grant option for update (granted_acl) on public.synthetic_catalog from synthetic_reader"],
    ["table grant", "grant select on public.synthetic_catalog to synthetic_reader"],
    ["schema grant", "grant create on schema public to synthetic_reader"],
    ["type grant", "grant usage on type public.synthetic_status to synthetic_reader"],
    ["routine grant", "grant execute on function public.synthetic_identity(text) to synthetic_reader"],
    ["default grant", "alter default privileges in schema public grant insert on tables to synthetic_reader"],
    ["role membership", "grant synthetic_group to synthetic_reader with admin option"],
    ["role capability", "alter role synthetic_reader bypassrls"],
    ["index definition", "drop index public.synthetic_partial_idx; create index synthetic_partial_idx on public.synthetic_catalog (lower(label)) where amount > 1"],
    ["view definition", "create or replace view public.synthetic_view as select id, upper(label) as label from public.synthetic_catalog"],
    ["policy predicate", "alter policy synthetic_public_update on public.synthetic_catalog with check (amount >= 2)"],
  ])("detects a changed %s rather than skipping the preservation check", async (_name, ddl) => {
    const before = sha256(await snapshot());
    await db.exec(ddl);
    expect(sha256(await snapshot())).not.toBe(before);
  });

  it("excludes only the six reserved policies on storage.objects during a new Storage install", async () => {
    const before = sha256(await snapshot("storage"));
    // Static reserved identifiers; fixtures exercise exclusion scope only,
    // not the migration files or the actual policies' authorization behavior.
    for (const name of STORAGE_POLICIES) await db.exec(`create policy ${name} on storage.objects for select using (true)`);
    expect(sha256(await snapshot("storage"))).not.toBe(before);
    expect(sha256(await snapshot("storage", true))).toBe(before);
    const storage = await metadata("storage", true);
    expect(named(storage.relations, "objects").policies.some((policy) => policy.name === "shagun_media_not_reserved")).toBe(true);
    expect(named(storage.relations, "synthetic_other_objects").policies.some((policy) => policy.name === "shagun_media_admin_read")).toBe(true);
    expect(named((await metadata("public", true)).relations, "synthetic_catalog").policies.some((policy) => policy.name === "shagun_media_admin_read")).toBe(true);
    await db.exec("alter policy synthetic_sibling_policy on storage.objects using (false)");
    expect(sha256(await snapshot("storage", true))).not.toBe(before);
  });

  it("excludes only internal triggers for the exact new admin FK, not sibling FKs or user triggers", async () => {
    const before = sha256(await snapshot("auth"));
    expect(named((await metadata("auth")).relations, "users").triggers.some((trigger) => trigger.internal)).toBe(true);
    await db.exec(`create schema shagun;
      create table shagun.admin_users (id uuid primary key,
        constraint admin_users_id_fkey foreign key (id) references auth.users(id))`);
    expect(sha256(await snapshot("auth"))).not.toBe(before);
    expect(sha256(await snapshot("auth", false, true))).toBe(before);
    await db.exec(`create table shagun.synthetic_other_links (id uuid primary key,
      constraint admin_users_id_fkey foreign key (id) references auth.users(id))`);
    expect(sha256(await snapshot("auth", false, true))).not.toBe(before);
    await db.exec(`drop table shagun.synthetic_other_links;
      create trigger synthetic_user_trigger before insert on auth.users
        for each row execute function public.synthetic_before()`);
    expect(sha256(await snapshot("auth", false, true))).not.toBe(before);
    expect(named((await metadata("auth", false, true)).relations, "users").triggers.some((trigger) => trigger.name === "synthetic_user_trigger" && !trigger.internal)).toBe(true);
  });

  it("does not read routine bodies or role/function configuration into metadata", async () => {
    const before = sha256(await snapshot());
    await db.exec(`create or replace function public.synthetic_identity(value text) returns text
      language sql immutable strict as $$ select value || 'synthetic-body-not-metadata' $$;
      alter function public.synthetic_identity(text) set synthetic.setting = 'synthetic-function-config-not-metadata';
      alter role synthetic_reader set synthetic.setting = 'synthetic-role-config-not-metadata'`);
    const after = await snapshot();
    expect(after.includes("not-metadata")).toBe(false);
    expect(sha256(after)).toBe(before);
  });

  it("returns no fabricated snapshot for a missing managed schema", async () => {
    await db.exec("drop schema auth cascade");
    const query = metadataSnapshotQuery("auth", false, false);
    const result = await db.query(query.text, query.parameters);
    expect(result.rows.length === 0).toBe(true);
  });
});